version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/Spanishnook:cached
    command: sleep infinity
    ports:
      - "3000:3000"
      - "9000:9000"
    environment:
      - NODE_ENV=development
